sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tPaKDZ3JfPxEKJfrHRE
    access-key-secret: t7XAwIqdhqKVt7XuQ94fbVGTzINbnT
    bucket-name: sky-p1sto

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wxab879cf1cd4eb404
    secret: 09cef5cbdc2ebf2462f74c497e0056de

  shop:
    address: 宜宾市翠屏区沙坪街道

  baidu:
    ak: vGHtxxyC39kHu2wqBmfS4Km6boXHPNYH